rank: 16
# Note: alpha is hardcoded to equal rank in the Diffusers SDXL LoRA script
lr: 0.0001
train_batch_size: 1
gradient_accumulation_steps: 4
max_train_steps: 250
lr_scheduler: cosine
lr_warmup_steps: 100
guidance: 7.5
trigger_word: cybrn
caption_template: "a painting in the style of {trigger}, "
